server.port=8081
spring.application.name=booking-service
spring.datasource.url=jdbc:postgresql://localhost:5433/hestia_booking
spring.datasource.username=oumaima
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

minio.endpoint=http://localhost:9000
minio.public-url=http://localhost:9000
minio.accessKey=admin
minio.secretKey=password123
minio.bucket=room-images
logging.level.okhttp3=DEBUG
logging.level.io.minio=DEBUG